travis:
  secure:
    BINSTAR_TOKEN: qCAJU+Ffcw3+iLvTx8vs5N/DeS9ibv1TAAGg7jzVd1PHyamYCnKkWvf/2PtPhpTRndTNurWZZKJnlEnv0xkzC5WQb5rPgXdyNHJSyf3jLCcLPH0BBBJy8sIIUVnk52JTBgTZnlJDkxZl7UN80cKNbeIbPxFpgXHaXfIcj0SEfKPrtuE/grdoE3miuVQkTWdaFHtQoeyHZJHXTqcZKugLvUQ2u4P3u6g0FH9zJq0QcziCTDH2gLSGjFGy6X5TFBukGAksKbiuFXbZAx1liAFCzvw2VQUzEeAzUDdBu6jLzC+UErpNFlhul1dfB3YcjtD0A9BP2num/nFCBlB4w8D+lqvnu5rBgr54stkskdWW8WgXAe6JWN0/DdqJgXVMiZoV7KQbqRXCm27ky7W4bWX/5XaA6NhJuho2fnQOM3Vjx4nxbYTx5EKv3iSInWhKg4xCcdDpqO/RNHjDzDEar7VofNw9yGvFJJHjUV9hqZqfDwlmEKfn/4ZoBuhLmyzSyTaqAXOW6DwyM5GIQpzQoArkkIrV6s3E4v3Jm0wJ6FICCvVM8ZWPdBMlXrCiiMjyVHNeMa61PMdPwAoLEgIkrdfdNOyBTKjfdbOURdCwHY6pJFPC7aX30dFoeiPWym3Xv2hQb3Zzwm0D9SbMBKhnt8GIDDgySK468oE8fBBxJ1ATt00=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
