travis:
  secure:
    BINSTAR_TOKEN: 1TBMAfk9aKsGD9G49mKRVxVQtro8OPCSUtTvJkT4ly3PWcVTxcm9x+6083bUFGih7+qOHuJheW2rJQAZdYhtDh2EyxWOmP774FnnXgM89MoOw7yT23jJ6PaudB53roEucbBlOzKEJHt4f4j3Q33rh+h+dlRJvnrWqm03fAM3wyACGKcK1cxx2rrjWF++3tJP3xirFO5S7gLIcxPP04cQq2G4IFcPtfh/uDu011sxo3wCiH/tM9d1/r26cMqPEY3hPKlqmoKEm8ctd3XGG2iYk2opxBocp+lqCosfBeodCLc1BCfztXB2EIlBmyTX5c+87qNRDteVrdCfyZYcyxhC+uu7/dEbN4RoYeZ0KHTIoEt4fY9koG0Bd5k5efAfchZ53aT2WCpErodxe4T4O4rx3RtoiWwdJtO2VHb0wC1umkdP82LzT9FpTGubRS0pzAxxzanXyL1M2GOHjSR2uZHPOBddb9DFxbIUdZbcv142eYHhdO03qaSeoCeMC1n9jmvv1700/ZeDJppOkB9c/rTHI20+01y25YDjfeHWMZE2aPs3ASWfSSc5fsfLS2RB8EpTIr2mmHK7zmjXUinPzvh/KmTNie3dLIDMR6hwTvApmtzaJLAlV1c7zvABSmNQaNLcaLdwvvubtWE1rMnykeoGF2wsghkXh3YoutR34025Cxk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
