travis:
  secure:
    BINSTAR_TOKEN: H6fCNWn33AYmqgKs8Qn6xHxwqYIk3owi/HEJ7pLlLFD+W04iTI+vzFRk1IKotxcBSzupAgkQ/jhbZZeZcCVHngaKvgmNm414DW8NaxaPM8lwsNW7BKcL4Kk8jbQb5g6Da37PyW7Wbgv60yCVUA1TePOfnyBqwOZbVdD8Ob1IRa3fP1FVzXShLFOMuzmu+UcaqUg+9ALQWjCO1L2yns7J43XfBR0PD4poFiNz09lqkFrTLgSfiPnebHEHpMUN46E8uUSW8WalYxC7HKVc9Osuj0Qfo8dDQ4U8OSrcUwLGrSol+IB9ywHvG6ygNQVVb8T3wMK5rHUrBV+ymwWn+OG6oTRkAnHb6MSIKYomdRBkq6y935gPPw5xDKmAYKORudDBebni3qpQoMTImSq+8kEo6OUa1LxJDyB0MAwAZ+e+U7xJfDjYCzw7RmoBmajMKLdtyzZXFXQdaQXcP3xkedUM9vwlrZERdaTJ8hhRPm6h4Ima//sXre7abEhUtaVedKK06pYlS4m93P2dbX5Yy0kH8gXPkFZjyOmWgvLhdKVPpHnkFlw/U4pwnVhTA/ILL3YgiqBRYrZ0Jax8VdoVuyXnWlu9j/ofdzQVQ0fmMoBOrQnw6NlWmBbnIVka+HIu/QBzMrEDIVDqjqIySbmensJESxar9vIEYaoDVx/FP6y+81M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
