travis:
  secure:
    BINSTAR_TOKEN: vwmgn/O9clj+b7o3kknghmj/7H8EZ72NLI0XIMGS4ZMcGLXzQ61vsxy5kBjZP36sQJxeNHvz8xTPW8wYLfikzDb5rKLcmmowKSQBwDLomRJQ0b2C9/jUuUyZpIKURgyS4QXp+057jfeHl+SXvJs0grbv0WfXeg/tO6nVr1oHXMibj/DrQO2pIENE0Afu1Unn4PPuiNF3a0WSs/hOaWV3W7Q86S3nlwXfs2lOrrK1Ho3gfmbP/vD/5mkXYoGo3iHnbBbImG2xfW2KAZfieTKDSeA4iYPP8kizmX1SbluA9yY8/CZlbcIcfTWZ35ecgsrFx7ghL263koV5lVbhrIAD7iNpisHl/LTYei0ZqFfzNytSvDHNzdcpacfe+bTfhtiP+BZS3frQUOwm0tC2vsiG4xcu6p0SjKpVn9R5jqlxqJhyhNj/I9lspuPw/JG4Ro7WfYH5/u1VTc5FnAcIqTXPY/FF76SkhOMjswunBYbgeGaD/+VqOF7Y80ISXEemR8BslDCvYl7i+QrZe93B3TiW+YqvNUJ8Go6de3kTqqFprsdMtbHT2P8N9q6XbJQQcc7Ev7Yc/Fj9Ep9I2rGmMvrcF/XaUsJ9LuCN+oh3lcXOpKJ1qiZh9kmFMnxnThr4DjQlTVjC0Q4oShoYoUvf3L+3NSiCu/9wZQ2QgAEfIEYK8cI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
