travis:
  secure:
    BINSTAR_TOKEN: qXpB5dyy6CaxKeShi0Bn0DwNG9CRAPvk4xeUQDy4uiXm6s3ov/O9mJzOvNUlisBPdgcV53MfA/uqhDTEwt/DH3lb4/IJEUpC1PXNvKAbEmSv5kDvYVb2wamNhe8Hy1Pz2rE5+KYSPfr7f0+96ERRDa6PeVS4aTD2wBBKYCDTFQpfCYzfT/wIhqAc6nqQxyxbbEwZAsqicp+kZ6EspsigRr2s1bOzd/eD1QoTZ3JMrmq0xNg5g+2ektPFtUMMJLKqcg+gi2vlYwq0amg9b8Dw88BPfEMNxrac+x9c1MpUiTSQ12ZEwUHZDe5ExeAxMRAzjpo3u/5pQNqnB6cY+/w1veLxRI7NH+K/V+gyEQKPuJPB/KvwoKMaUKYdIMELGFbq7kpUlhFAl00ugqEpgySKhLSXvZX/BZUZABWeCXr5U1vgS+p5bPPtEVn0nkotJ97s+gnY6GQzNUSssn0GoQsLyuqP8K3DPYJBaeKwx0D3N8riwaQV9W1/PNLYODwDOICvNaxCA2tc8iyt2AkKwwRgqV6WHyA0BM27DDYuRCJ4/dWc1v34tQ9eiIF+qZsy+g7Auxk4KALO9qZ3HXlR25vxLXk+po7AuaCH1M9U5OeKQ96WSQQ83hpz5FkjN+XEZa6il5W647prY9J6lWmYaKHlnoWz30TN65rvaFviVNwZXFs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
