travis:
  secure:
    BINSTAR_TOKEN: 4S+aeElqBDzBswlGaeYsNf09BfOAcmcm1OmrXGsmZCdWAesZb74tMAyyUPj5M0Qlm4Wa/k+3IPqPe8FJobrsA+dODXDuIJrwSyOm/qTXbMX0rYWWSD4QabIbLyU/xlZUlwvE5cLXGjYyDJth76aKQ7PI4tg8wii1yLrYvSZT4AEDtn3P2cGXMHldfzdsQttB9mlqTL/iB6Do+RtHog9FOo2I+N7994mwZIXtXh6r3a0qqrIqD/rqZay+ruWXl/X1lYdn5gUQRHSP9/U/hfZeKVfVhZJBWfskUYryqufYaW6MyT6UF3eulhQgX7n3+1uAjWgAqCZ3M8/vas74gwM3ct0q0BmYua8GivAeRm5Z3UmmRsRsgy2mtfMJSs/SrjdBwcjJDkBXQEXb/V7zHmm2Yman37UDZHGddB6QqMtLom8af1NkRwFSQ0noHVD/6Mt8YmmVMidT5UkqHdUnNbs25/7m3R2ILE1bFiO+VSqg+7Qk4lLZElRCSYFsf6uuUSvJWxpeUg4ynxL0bsCPFcLvc6JrnkqA8zs6iC5zh9pO/X1cag9kSvLJV1tOEp0kMpU7eKJ74aa0im9XkqjRMA7T1hfR3UVUOF6BBZDpbxL/X1SEa1VP2nGDpl91P4kb0Cnds6VGZd28ISRhZR1qV59c2vLj4WZMnxg+M1yPeHDk7Jk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
