travis:
  secure:
    BINSTAR_TOKEN: CgXPwlH8ZDauYmi3L5pC3xnCTNy0wnWi5vi5qfGmT34BcewpcwzAnFcOlDY469jpZqB4xNBLE9Q0sVuyWnxktjO57CR2MpVpPEu/xqDp/N2TX8gP12tJ8tF0fieRUgp9LRRrLz88qM7VUhEx2Q9JHhhkSLKKemfzO2svROte4BjlNr0e+WgIqsKR9wTjAg8U3iv2pfvaJ2gXOsJoQ3nsSBZhJ0OzmJz2CjssbV45Zyhu5k9DqVTVJLwyS3Ny2XfSwiJ1TNOE9V/ZB0V0J6MeQEgevDjAw9lMhx+fCPvfOwJjYHo81CMFA12OgchSu7N86PhwglCY0GHwaulTFgUg97v+0YHItXDkHO+EvJPg0uu1ZJph16bE7Aw4/dmEJgq8BDQ2yXSViRWUoxueXtgmORsvuMdaIMvMRq5T2QqXgB8/fegUqXHxZBwEHXv6KNuqczYOVkyNJa1ST5i6pZRwloMvZA6qHyaCGG36MIOYWnLyDZC5DkZjRmXUgD4zwcFfU5c8hzwXgWGx68cF8eljturnAefS2R5VZn/MuL8eDBZAFeLgwUMpKYIluLrMCSvooXby+0rPthkicpEBPzMng7DYWXKOu/xbya9aQGrZVfPdnUfngVRI+Zb6ZKueHNdawcbj24F8y2fIu3mtHD50sEkZ94klfSPi18Pw6Ogq3uQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
