travis:
  secure:
    BINSTAR_TOKEN: A3H3PVau8K8S2UfOhC38TxCPWKdn6ghyCC7Be6vH4wNEtTmy0hZ/8ZxzkpyV5HiaE4+X5D7FwAOlaKY97qs6BNExPziikbnWSnIAXjiBD2TZwGvNVHfPkEizLr0DuWQF2cYp2JLtNnjacIHNqK2x3x85tVV95J6FvyL+tFt4KYgSgkuPNwoRs/6+jdOKWFyhtZsztGpcxssKDNKNlxxYKbcjbjhz9f+YwywpL1GuzQCKvlQDJzjEi+I1dAD44SJl6pmycbXsGhSdWGbzY63MYD+POcbWnAw6sPRodk6LYQUDSjYRsowzmfE+5O7CJbrMLXjBpI3zsP967p3Cgnhg8QVunX7uluTppCLmULPThB68KqSwcFOKBtfYQIbqc7ybFu7EPvGUFgihsCcRkM7wALIZy7qkJ+KC4eGozyViQzPm0QGBYP1o2hn0Sy7Jfw1OIvDrxpUDncEmXm5SgGta7OEpp8MDf6w3P7Bd5yC5jaZX//D20t6iJtdZGV4tGTeV0vwtzTk2BFw999A6E3Yw24ms7kjEF+pEen3TD0p68OEvA4e0qtmzJ+U6SLSu7nmI0G3IOqJIh18g6MC5qaxvE1v7lLIQF2LVoxYMNid/6aQOa8uliQjtnZhqGjnA30ECPElqNWaObwoQQ6anysEPErx/OlNsd3MkX4W8+MDRK14=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
